version: "3"
services:
  pgdb:
    container_name: postgres_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ${DC_CONFIG_FILE:-.development.env}
    volumes:
      - pg_db_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/20_osm_data.sh
  
  app:
    container_name: wafflemap
    build:
      context: .
      dockerfile: ./docker/wafflemap/Dockerfile
    restart: always
    ports:
      - ${DC_WM_EXPOSE_PORT}:8080
    depends_on:
      - pgdb
    env_file:
      - ${DC_CONFIG_FILE:-.development.env}

volumes:
  pg_db_data:
  pg_admin_data: