version: "3"
services:
  pgdb:
    container_name: postgres_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ${DC_CONFIG_FILE:-.development.env}
    ports:
      - ${DC_POSTGRES_EXPOSE_PORT:-5432}:5432
    volumes:
      - pg_db_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/20_osm_data.sh

  pgadmin4: # pgadmin4 is only available on development
    container_name: postgres_pgadmin4
    image: dpage/pgadmin4:8.9
    restart: always
    depends_on:
      - pgdb
    env_file:
      - ${DC_CONFIG_FILE:-.development.env}
    ports:
      - ${DC_PGADMIN_EXPOSE_PORT:-5000}:80
    volumes:
      - pg_admin_data:/var/lib/pgadmin

  app:
    container_name: wafflemap
    restart: no
    entrypoint: ["echo", "the wafflemap service is disabled during development"]
  
volumes:
  pg_db_data:
  pg_admin_data: