version: "3"
services:
  pgdb:
    container_name: postgres_db
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .development.env
    ports:
      - "5432:5432"
    volumes:
      - pg_db_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sh:/docker-entrypoint-initdb.d/20_osm_data.sh

  pgadmin4:
    container_name: postgres_pgadmin4
    image: dpage/pgadmin4:8.9
    restart: always
    depends_on:
      - pgdb
    env_file:
      - .development.env
    ports:
      - "5000:80"
    volumes:
      - pg_admin_data:/var/lib/pgadmin
  
  app:
    container_name: wafflemap
    build:
      context: .
      dockerfile: ./docker/wafflemap/Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - pgdb
    env_file:
      - .development.env

volumes:
  pg_db_data:
  pg_admin_data: